# Generated by Django 5.2.1 on 2025-07-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_atencion_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('atendido', 'Atendido'), ('no_asistio', 'No asistió'), ('completada', 'Completada')], max_length=10, verbose_name='Estado de la Cita'),
        ),
    ]
